{% set name = "retropath2_wrapper" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/retropath2-wrapper/archive/{{ version }}.tar.gz
  sha256: 6e3ee1af4dce5a550ecb5041197d654fdebd39a12be463845ca02f0abfa01920

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - brs_utils
    - filetype
    - colored
    - freetype

test:
  source_files:
    - tests
  imports:
    - {{ name|lower }}
  requires:
    - pytest
  commands:
    - python -m {{ name|lower }} --help
    - cd tests
    - pytest -v

about:
  home: https://github.com/brsynth/{{ name|lower }}
  summary: Python wrapper to run RetroPath2.0 KNIME workflow
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - breakthewall
    - kenza12
